version: '1'
services:
  web:
    build: .
    command: php -S 0.0.0.0:8000 -t /app
    ports:
    - "5000:5000"
    volumes:
    - .:/code
    - logvolume01:/var/log
    links:
    - db
    - node
  node:
    image: nodesource/node:trusty
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: docker
